# Generated by Django 6.0.6 on 2026-06-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardapioDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True, verbose_name='Data do Cardápio')),
                ('dia_semana', models.CharField(max_length=20, verbose_name='Dia da Semana')),
                ('lanche_manha', models.TextField(blank=True, null=True, verbose_name='Lanche da Manhã')),
                ('almoco', models.TextField(blank=True, null=True, verbose_name='Almoço')),
                ('lanche_tarde', models.TextField(blank=True, null=True, verbose_name='Lanche da Tarde')),
                ('eja', models.TextField(blank=True, null=True, verbose_name='Jantar / EJA')),
                ('zinco', models.CharField(blank=True, max_length=20, null=True, verbose_name='Zinco (ZN)')),
                ('sodio', models.CharField(blank=True, max_length=20, null=True, verbose_name='Sódio (NA)')),
                ('vitamina_a', models.CharField(blank=True, max_length=20, null=True, verbose_name='Vitamina A (VITA)')),
                ('vitamina_c', models.CharField(blank=True, max_length=20, null=True, verbose_name='Vitamina C (VITC)')),
                ('fibra', models.CharField(blank=True, max_length=20, null=True, verbose_name='Fibra (FIB)')),
                ('eh_feriado', models.BooleanField(default=False, verbose_name='Feriado / Ponto Facultativo')),
                ('observacao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observações')),
            ],
            options={
                'verbose_name': 'Cardápio do Dia',
                'verbose_name_plural': 'Cardápios dos Dias',
                'ordering': ['data'],
            },
        ),
    ]
