"""
Django settings for backend_api project.

Generated by 'django-admin startproject' using Django 6.0.6.
"""

import os
import dj_database_url
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SEGURANÇA: Chave secreta em produção deve vir de variável de ambiente
SECRET_KEY = os.getenv(
    "SECRET_KEY", "django-insecure-9s+xrx3rx3qon-at_o$f9hza3oq3%z4()zkot9ww90zvpxo1_)"
)

# DEBUG desativa automaticamente se não estiver em ambiente local
DEBUG = os.getenv("DEVELOPMENT", "True") == "True"

# Permitir localhost para desenvolvimento e os domínios do Railway para produção
# Permitir localhost, domínios do Railway e o seu domínio próprio em produção
ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    ".railway.app",
    "alphaomegainfo.ong.br",
    "www.alphaomegainfo.ong.br",
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Bibliotecas de Terceiros
    "rest_framework",
    "corsheaders",
    # Seus Apps Criados
    "cardapio",
    "financeiro",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    # Middleware do CORS inserido no topo (obrigatório por documentação)
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend_api.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend_api.wsgi.application"


# Database Configuration
# Configuração Dinâmica do Banco de Dados (Suporta conexões Locais e em Produção)
# Configuração Dinâmica do Banco de Dados (Suporta conexões Locais e em Produção)
# Configuração Inteligente do Banco de Dados
# Se houver a variável RAILWAY_ENVIRONMENT, significa que o código está rodando na nuvem do Railway.
if os.getenv("RAILWAY_ENVIRONMENT"):
    DATABASES = {"default": dj_database_url.config(conn_max_age=600, ssl_require=True)}
else:
    # Caso contrário, você está no seu computador local (Omega). Usa o SQLite super rápido e offline.
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# Internacionalização e Localização (Ajustado para o Brasil)
LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# Configurações de Arquivos Estáticos (Essencial para o painel Admin no Railway)
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"


# Configurações do CORS (Permite que o React/Vue consuma a API)
CORS_ALLOW_ALL_ORIGINS = (
    True  # Em produção estrita mudamos, mas para desenvolvimento facilita muito
)

# Configuração do CORS para Desenvolvimento Local
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # Porta padrão do Vite (React / Vue)
    "http://localhost:3000",  # Outra porta comum de frontend
]
